### ISSUE TITLE
打开应用后（未按音量下键解锁）桌面会出现隐藏的应用

### ISSUE THREAD

**Issue by xiaoyv404** [ljlVink/LinspirerDemo#3]
版本为最新构建版本
commit hash：78dccaaafd1cb7aeaa119342509bca038a14fd51
设备：荣耀平板8
系统：Magic UI 6.1.0
领创桌面版本：tongyongshengchan_5.04.105.1

**Comment by ljlVink** [comment]
![Screenshot_2023-12-02-10-55-16-684_com.github.android-edit.jpg](https://github.com/ljlVink/LinspirerDemo/assets/46098706/9bb76cbb-dc1a-4480-97d8-0d92166e5931)

**Comment by ljlVink** [comment]
自适应即可

**Comment by xiaoyv404** [comment]
> 自适应即可

(#ﾟДﾟ)这这这，为什么不弄成进入主页后呢
